# Generated by Django 5.2.3 on 2025-06-18 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("recipes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("image_recognition", "Image Recognition"),
                            ("recipe_generation", "Recipe Generation"),
                            ("ingredient_suggestion", "Ingredient Suggestion"),
                            ("meal_planning", "Meal Planning"),
                        ],
                        max_length=25,
                    ),
                ),
                ("input_text", models.TextField(blank=True)),
                (
                    "input_image",
                    models.ImageField(blank=True, null=True, upload_to="ai_requests/"),
                ),
                ("response_text", models.TextField()),
                ("processing_time", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "generated_recipe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="recipes.recipe",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FoodRecognition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("detected_foods", models.JSONField(default=list)),
                ("confidence_score", models.FloatField()),
                (
                    "ai_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_recognition",
                        to="ai_assistant.airequest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecipeGeneration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ingredients_provided", models.TextField()),
                ("dietary_restrictions", models.CharField(blank=True, max_length=200)),
                ("cuisine_preference", models.CharField(blank=True, max_length=50)),
                ("difficulty_preference", models.CharField(blank=True, max_length=10)),
                ("time_constraint", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "ai_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_generation",
                        to="ai_assistant.airequest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AIFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("helpful", "Helpful"),
                            ("not_helpful", "Not Helpful"),
                            ("incorrect", "Incorrect"),
                            ("incomplete", "Incomplete"),
                        ],
                        max_length=15,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ai_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="ai_assistant.airequest",
                    ),
                ),
            ],
            options={
                "unique_together": {("ai_request", "user")},
            },
        ),
    ]
