# Generated by Django 4.2.4 on 2025-08-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airequest",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("image_recognition", "Image Recognition"),
                    ("recipe_generation", "Recipe Generation"),
                    ("ingredient_suggestion", "Ingredient Suggestion"),
                    ("meal_planning", "Meal Planning"),
                    ("general_chat", "General Chat"),
                ],
                max_length=25,
            ),
        ),
    ]
