# Generated by Django 5.2.3 on 2025-08-07 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0002_alter_airequest_request_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airequest",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("image_recognition", "Image Recognition"),
                    ("recipe_generation", "Recipe Generation"),
                    ("ingredient_suggestion", "Ingredient Suggestion"),
                    ("meal_planning", "Meal Planning"),
                ],
                max_length=25,
            ),
        ),
    ]
