# Generated by Django 5.2.3 on 2025-06-18 15:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="recipes/"),
                ),
                (
                    "prep_time",
                    models.PositiveIntegerField(
                        help_text="Preparation time in minutes"
                    ),
                ),
                (
                    "cook_time",
                    models.PositiveIntegerField(help_text="Cooking time in minutes"),
                ),
                ("servings", models.PositiveIntegerField(default=4)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "cuisine",
                    models.CharField(
                        choices=[
                            ("italian", "Italian"),
                            ("chinese", "Chinese"),
                            ("mexican", "Mexican"),
                            ("indian", "Indian"),
                            ("american", "American"),
                            ("french", "French"),
                            ("japanese", "Japanese"),
                            ("thai", "Thai"),
                            ("mediterranean", "Mediterranean"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_public", models.BooleanField(default=True)),
                (
                    "calories_per_serving",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("protein_grams", models.FloatField(blank=True, null=True)),
                ("carbs_grams", models.FloatField(blank=True, null=True)),
                ("fat_grams", models.FloatField(blank=True, null=True)),
                ("fiber_grams", models.FloatField(blank=True, null=True)),
                ("ai_generated", models.BooleanField(default=False)),
                (
                    "source_image",
                    models.ImageField(blank=True, null=True, upload_to="ai_source/"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("quantity", models.FloatField()),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("cup", "Cup"),
                            ("tbsp", "Tablespoon"),
                            ("tsp", "Teaspoon"),
                            ("oz", "Ounce"),
                            ("lb", "Pound"),
                            ("g", "Gram"),
                            ("kg", "Kilogram"),
                            ("ml", "Milliliter"),
                            ("l", "Liter"),
                            ("piece", "Piece"),
                            ("slice", "Slice"),
                            ("clove", "Clove"),
                            ("bunch", "Bunch"),
                            ("can", "Can"),
                            ("package", "Package"),
                            ("to_taste", "To taste"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredients",
                        to="recipes.recipe",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="RecipeTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "recipes",
                    models.ManyToManyField(
                        blank=True, related_name="tags", to="recipes.recipe"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Instruction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_number", models.PositiveIntegerField()),
                ("instruction", models.TextField()),
                (
                    "time_minutes",
                    models.PositiveIntegerField(
                        blank=True, help_text="Time for this step in minutes", null=True
                    ),
                ),
                (
                    "temperature",
                    models.CharField(
                        blank=True,
                        help_text="Cooking temperature if applicable",
                        max_length=50,
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructions",
                        to="recipes.recipe",
                    ),
                ),
            ],
            options={
                "ordering": ["step_number"],
                "unique_together": {("recipe", "step_number")},
            },
        ),
        migrations.CreateModel(
            name="RecipeFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="recipes.recipe",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("recipe", "user")},
            },
        ),
        migrations.CreateModel(
            name="RecipeRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("review", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="recipes.recipe",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("recipe", "user")},
            },
        ),
    ]
